FROM node:24.17.0-alpine AS build

WORKDIR /app
COPY frontend/package.json frontend/package-lock.json ./
RUN npm ci
COPY frontend ./
RUN npm run build

FROM alpine:3.22
WORKDIR /out
COPY --from=build /app/dist /out
CMD ["sh", "-c", "cp -R /out/* /usr/share/nginx/html && sleep infinity"]
