# Generated by Django 6.0.6 on 2026-06-18 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
        ('operations', '0001_initial'),
        ('people', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='people.workerprofile'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='operations.checklistitem'),
        ),
        migrations.AddField(
            model_name='checklisttemplate',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_templates', to='services.service'),
        ),
        migrations.AddField(
            model_name='checklistitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.checklisttemplate'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='property',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='crm.property'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order', to='services.quote'),
        ),
        migrations.AddField(
            model_name='qualityreview',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quality_reviews', to='operations.workorder'),
        ),
        migrations.AddField(
            model_name='incident',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='operations.workorder'),
        ),
        migrations.AddField(
            model_name='checklistresult',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_results', to='operations.workorder'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='operations.workorder'),
        ),
    ]
