# Generated by Django 6.0.6 on 2026-06-18 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingIntegrationIntent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(max_length=120)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('supplies', 'Insumos'), ('transport', 'Transporte'), ('payroll', 'Remuneraciones'), ('contractor', 'Honorarios'), ('equipment', 'Equipo'), ('other', 'Otro')], max_length=24)),
                ('description', models.CharField(max_length=220)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('CRC', 'CRC'), ('USD', 'USD')], default='CRC', max_length=3)),
                ('incurred_at', models.DateField()),
                ('vendor', models.CharField(blank=True, max_length=160)),
                ('receipt', models.FileField(blank=True, upload_to='expenses/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('CRC', 'CRC'), ('USD', 'USD')], default='CRC', max_length=3)),
                ('method', models.CharField(choices=[('sinpe', 'SINPE'), ('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('card', 'Tarjeta'), ('other', 'Otro')], max_length=24)),
                ('paid_at', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=160)),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
