# Generated by Django 6.0.6 on 2026-06-18 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(max_length=160)),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('preferred_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English')], default='es', max_length=2)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('delinquent', 'Moroso')], default='active', max_length=24)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('pets', models.TextField(blank=True)),
                ('special_instructions', models.TextField(blank=True)),
                ('referral_source', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('role', models.CharField(blank=True, max_length=80)),
                ('is_primary', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='crm.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=32)),
                ('preferred_language', models.CharField(choices=[('es', 'Espanol'), ('en', 'English')], default='es', max_length=2)),
                ('source', models.CharField(blank=True, max_length=80)),
                ('utm', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'Nuevo'), ('contacted', 'Contactado'), ('qualified', 'Calificado'), ('won', 'Convertido'), ('lost', 'Perdido')], default='new', max_length=24)),
                ('requested_service', models.CharField(blank=True, max_length=120)),
                ('message', models.TextField(blank=True)),
                ('consent_data_processing', models.BooleanField(default=False)),
                ('consent_marketing', models.BooleanField(default=False)),
                ('next_follow_up_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.CharField(choices=[('phone', 'Telefono'), ('email', 'Correo'), ('whatsapp', 'WhatsApp'), ('internal', 'Interno')], max_length=24)),
                ('direction', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=16)),
                ('subject', models.CharField(blank=True, max_length=160)),
                ('body', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.customer')),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='crm.lead')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('property_type', models.CharField(choices=[('home', 'Residencial'), ('office', 'Oficina'), ('vacation', 'Propiedad vacacional/Airbnb')], default='home', max_length=24)),
                ('address', models.TextField()),
                ('zone', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('area_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('bedrooms', models.PositiveSmallIntegerField(default=0)),
                ('bathrooms', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('floor_type', models.CharField(blank=True, max_length=120)),
                ('complexity_level', models.PositiveSmallIntegerField(default=1)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('inventory_notes', models.TextField(blank=True)),
                ('airbnb_check_in', models.TimeField(blank=True, null=True)),
                ('airbnb_check_out', models.TimeField(blank=True, null=True)),
                ('access_instructions', models.TextField(blank=True)),
                ('alarm_notes', models.TextField(blank=True)),
                ('restrictions', models.TextField(blank=True)),
                ('standard_minutes', models.PositiveIntegerField(default=120)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='crm.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
