# Generated by Django 5.2.16 on 2026-07-14 16:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='consent_data_processing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='consent_marketing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('individual', 'Persona'), ('business', 'Empresa'), ('property_manager', 'Administrador de propiedades')], default='individual', max_length=24),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='source_lead',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='converted_customer', to='crm.lead'),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='property',
            name='frequency',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='operational_notes',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity_type', models.CharField(choices=[('note', 'Nota'), ('contact', 'Contacto'), ('status', 'Cambio de estado'), ('assignment', 'Asignación'), ('conversion', 'Conversión')], max_length=24)),
                ('detail', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='crm.lead')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
