# Generated by Django 6.0.6 on 2026-06-18 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker_type', models.CharField(choices=[('employee', 'Personal laboral'), ('contractor', 'Prestador independiente')], max_length=24)),
                ('full_name', models.CharField(max_length=160)),
                ('phone', models.CharField(max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('emergency_contact', models.JSONField(blank=True, default=dict)),
                ('availability', models.JSONField(blank=True, default=dict)),
                ('zones', models.JSONField(blank=True, default=list)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('trainings', models.JSONField(blank=True, default=list)),
                ('references', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Activo'), ('inactive', 'Inactivo'), ('suspended', 'Suspendido')], default='active', max_length=24)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('contract_expires_at', models.DateField(blank=True, null=True)),
                ('ins_policy_status', models.CharField(blank=True, max_length=120)),
                ('ccss_status', models.CharField(blank=True, max_length=120)),
                ('compensation_terms', models.TextField(blank=True)),
                ('incidents', models.TextField(blank=True)),
                ('evaluations', models.JSONField(blank=True, default=list)),
                ('contractor_exclusivity', models.BooleanField(default=False)),
                ('contractor_fixed_schedule', models.BooleanField(default=False)),
                ('contractor_direct_supervision', models.BooleanField(default=False)),
                ('contractor_company_tools_required', models.BooleanField(default=False)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkerPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='CRC', max_length=3)),
                ('paid_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.workorder')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='people.workerprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
